// Pure detector. Strict thresholds; no interpolation across missing/conflicting values or gaps.
function detectAnomalies(rows,rule){
 const byTime=new Map();for(const r of rows){if(!Number.isFinite(r.time))continue;const v=Number.isFinite(r.value)?r.value:null;if(byTime.has(r.time)&&byTime.get(r.time)!==v)byTime.set(r.time,null);else if(!byTime.has(r.time))byTime.set(r.time,v)}
 const sorted=[...byTime].sort((a,b)=>a[0]-b[0]),events=[],history=[];let run=null,left=0,last=null;
 const finish=()=>{if(run){events.push(run);run=null}};
 for(const [time,v]of sorted){
  if(v===null||last!==null&&time-last>rule.gap){finish();history.length=0;left=0}if(v===null){last=null;continue}
  const kind=rule.high!==null&&v>rule.high?'high':rule.low!==null&&v<rule.low?'low':null;
  if(kind){if(run?.kind!==kind)finish();if(!run)run={kind,start:time,end:time,n:0,peak:v};run.end=time;run.n++;run.peak=kind==='high'?Math.max(run.peak,v):Math.min(run.peak,v)}else finish();
  while(left<history.length&&history[left].time<time-rule.window)left++;
  const ref=history[left];if(rule.jump!==null&&ref&&Math.abs(v-ref.value)>rule.jump)events.push({kind:v>ref.value?'rise':'fall',start:ref.time,end:time,n:2,peak:v,delta:v-ref.value});
  history.push({time,value:v});last=time;
 }finish();return events.sort((a,b)=>a.start-b.start||a.end-b.end);
}
const anomalyPanel=document.createElement('section');anomalyPanel.className='card anomaly-panel';anomalyPanel.innerHTML='<div class="section-heading"><h2>異常快速檢查</h2><button id="scanAnomalies" class="primary">檢查所選期間</button></div><p class="help-text">使用所選期間的原始紀錄，不套用數值篩選或查詢子集；僅標記，不刪除資料。門檻非安全標準。</p><details id="anomalySettings" open><summary>① 設定判斷門檻（先設定，再檢查）</summary><div class="anomaly-rules">'+keys.map(k=>'<fieldset><legend>'+label(k)+'（'+units[k]+'）</legend><label>低於<input id="anomalyLow-'+k+'" type="number" step="any" placeholder="不檢查"></label><label>高於<input id="anomalyHigh-'+k+'" type="number" step="any" placeholder="不檢查"></label><label>變化量超過<input id="anomalyJump-'+k+'" type="number" min="0" step="any" placeholder="不檢查"></label></fieldset>').join('')+'</div><div class="anomaly-options"><label>檢查來源<select id="anomalySource"><option value="hive">蜂箱內部</option><option value="weather">外部氣象站</option><option value="both">內部與外部</option></select></label><label>變化比較視窗（分鐘）<input id="anomalyWindow" type="number" min="1" max="1440" value="5"></label><label>持續超標：觀測跨度至少（分鐘）<input id="anomalyDuration" type="number" min="1" max="10080" value="10"></label><label>內部最大紀錄間隔（秒）<input id="anomalyGapHive" type="number" min="1" value="90"></label><label>外部最大紀錄間隔（秒）<input id="anomalyGapWeather" type="number" min="1" value="5400"></label><label class="check-tile"><input id="anomalyShade" type="checkbox" checked>圖表標示超標時段</label></div><p class="help-text">變化量與視窗內最早有效紀錄比較，使用嚴格大於／小於。缺值、衝突或過長間隔會中斷判斷；外站每小時一筆時，視窗至少設 60 分鐘。跨度不是推估持續時間，單點為 0。短暫與持續超標顏色可在圖表樣式中調整。陰影表示原始紀錄超標，平均線可能未超標；差值、每日疊圖與 24 小時平均圖不套用時段陰影。</p></details><p id="anomalyStatus" role="status">尚未設定門檻。</p><div id="anomalyCards" class="anomaly-cards"></div><div class="anomaly-actions"><button id="restoreAnomalyRange" class="secondary" hidden>返回檢查期間</button><button id="downloadAnomalies" class="secondary" disabled>下載標記 CSV</button></div><div id="anomalyList"></div>';
$('controlsCard').after(anomalyPanel);anomalyPanel.hidden=true;
const anomalyIds=['anomalySource','anomalyWindow','anomalyDuration','anomalyGapHive','anomalyGapWeather','anomalyShade',...keys.flatMap(k=>['anomalyLow-'+k,'anomalyHigh-'+k,'anomalyJump-'+k])];settingIds.push(...anomalyIds);
let anomalyEvents=[],anomalyRange=null,anomalyActive=false,anomalyNavigating=false,anomalySignature='';
function anomalyFingerprint(){return JSON.stringify([...anomalyIds.filter(id=>id!=='anomalyShade'),'startDate','endDate'].map(id=>value(id)))}
const renderBeforeAnomalies=render;render=function(){if(anomalyActive&&!anomalyNavigating&&anomalySignature!==anomalyFingerprint())invalidateAnomalies();renderBeforeAnomalies()};$('renderButton').onclick=render;
function invalidateAnomalies(){anomalyActive=false;anomalyEvents=[];$('anomalyCards').replaceChildren();$('anomalyList').replaceChildren();$('downloadAnomalies').disabled=true;$('anomalyStatus').textContent='資料或設定已變更，請重新檢查。'}
const setupBeforeAnomalies=setup;setup=function(){setupBeforeAnomalies();anomalyPanel.hidden=!(state.hive||state.weather);invalidateAnomalies()};
function anomalyRules(){const rules={};for(const k of keys){const read=part=>{const s=value('anomaly'+part+'-'+k);if(!s)return null;const n=Number(s);if(!Number.isFinite(n))throw Error('請確認'+label(k)+'的門檻');return n};const low=read('Low'),high=read('High'),jump=read('Jump');if(low!==null&&high!==null&&low>=high)throw Error(label(k)+'下限必須小於上限');if(jump!==null&&jump<=0)throw Error('變化量必須大於 0');rules[k]={low,high,jump,window:Number(value('anomalyWindow'))*60000}}
 for(const id of ['anomalyWindow','anomalyDuration','anomalyGapHive','anomalyGapWeather']){const n=Number(value(id));if(!Number.isFinite(n)||n<=0||n>604800)throw Error('時間與間隔必須為有效正數（不超過 604800）')}if(!Object.values(rules).some(r=>r.low!==null||r.high!==null||r.jump!==null))throw Error('請先輸入至少一項上下限或變化量門檻。');return rules}
const anomalyKind={high:'高於上限',low:'低於下限',rise:'突然上升',fall:'突然下降'};
function showAnomalyList(type){const subset=anomalyEvents.filter(e=>type==='all'?true:type==='threshold'?['high','low'].includes(e.kind):type==='sustained'?e.sustained:e.kind===type);$('anomalyList').innerHTML='<p class="help-text">共 '+subset.length+' 項，顯示前 100 項；點選可查看前後 30 分鐘。完整紀錄可下載。</p>'+subset.slice(0,100).map((e,i)=>'<button class="anomaly-event secondary" data-event="'+i+'">'+esc((e.source==='hive'?'內部':'外部')+label(e.key)+' · '+anomalyKind[e.kind]+' · '+local(new Date(e.start)).replace('T',' ')+' ～ '+local(new Date(e.end)).replace('T',' ')+' · '+(e.delta===undefined?'極值 '+e.peak.toFixed(2):'變化 '+e.delta.toFixed(2))+' '+units[e.key]+(e.sustained?' · 持續超標':''))+'</button>').join('');$('anomalyList').querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>focusAnomaly(subset[Number(b.dataset.event)]))}
function focusAnomaly(e){anomalyNavigating=true;$('startDate').value=local(new Date(Math.max(+new Date(anomalyRange.start),e.start-1800000)));$('endDate').value=local(new Date(Math.min(+new Date(anomalyRange.end),e.end+1800000)));$('chartMode').value='continuous';$('aggregation').value='raw';$('xTickInterval').value='auto';resetFilterValues();if(typeof clearQuerySubset==='function')clearQuerySubset();state.weatherEnabled=anomalyRange.weather;if($('weatherEnabled'))$('weatherEnabled').checked=state.weatherEnabled;$('restoreAnomalyRange').hidden=false;markDirty();render();anomalySignature=anomalyFingerprint();anomalyNavigating=false;$('chartCard').scrollIntoView({behavior:'smooth',block:'start'})}
$('restoreAnomalyRange').onclick=()=>{if(!anomalyRange)return;anomalyNavigating=true;for(const [id,v]of Object.entries(anomalyRange.settings))$(id).value=v;$('startDate').value=anomalyRange.start;$('endDate').value=anomalyRange.end;markDirty();render();anomalySignature=anomalyFingerprint();anomalyNavigating=false;$('restoreAnomalyRange').hidden=true};
$('scanAnomalies').onclick=()=>{invalidateAnomalies();try{const rules=anomalyRules(),start=+new Date(value('startDate')),end=+new Date(value('endDate'));if(!Number.isFinite(start)||!Number.isFinite(end)||start>end)throw Error('請先確認檢查期間');const sources=value('anomalySource')==='both'?['hive','weather']:[value('anomalySource')];let count=0,invalid=0;const skipped=[];
 for(const source of sources){const d=state[source];if(!d?.mapping.time){skipped.push(source==='hive'?'內部資料':'外部資料');continue}const records=Object.fromEntries(keys.map(k=>[k,[]]));for(const row of d.rows){const date=rowDate(row,d);if(!date){invalid++;continue}const time=+date;if(time<start||time>end)continue;count++;for(const k of keys){const s=String(row[d.mapping[k]]??'').trim();records[k].push({time,value:s&&Number.isFinite(Number(s))?Number(s):null})}}for(const k of keys){const rule={...rules[k],gap:Number(value(source==='hive'?'anomalyGapHive':'anomalyGapWeather'))*1000};if(rule.low===null&&rule.high===null&&rule.jump===null)continue;if(!d.mapping[k]){skipped.push((source==='hive'?'內部':'外部')+label(k));continue}for(const e of detectAnomalies(records[k],rule))anomalyEvents.push({...e,source,key:k,sustained:['high','low'].includes(e.kind)&&e.end-e.start>=Number(value('anomalyDuration'))*60000})}}
 anomalyEvents.sort((a,b)=>a.start-b.start);anomalyActive=true;anomalyRange={start:value('startDate'),end:value('endDate'),weather:sources.includes('weather')||state.weatherEnabled,settings:Object.fromEntries(['chartMode','aggregation','xTickInterval'].map(id=>[id,value(id)]))};$('restoreAnomalyRange').hidden=true;
 const cards=[['all','全部異常',anomalyEvents.length],['threshold','超標區段',anomalyEvents.filter(e=>['high','low'].includes(e.kind)).length],['sustained','其中持續超標',anomalyEvents.filter(e=>e.sustained).length],['rise','突然上升',anomalyEvents.filter(e=>e.kind==='rise').length],['fall','突然下降',anomalyEvents.filter(e=>e.kind==='fall').length]];
 $('anomalyCards').innerHTML=cards.map(([id,title,n])=>'<button class="secondary" data-kind="'+id+'"><strong>'+n+'</strong><span>'+title+'</span></button>').join('');$('anomalyCards').querySelectorAll('button').forEach(b=>b.onclick=()=>showAnomalyList(b.dataset.kind));$('anomalyStatus').textContent='已檢查 '+count.toLocaleString()+' 筆原始紀錄；無效時間 '+invalid+' 筆。'+(skipped.length?'未檢查：'+skipped.join('、')+'。':'')+'點選卡片定位時段；定位會切換原始資料並清除繪圖篩選。';$('downloadAnomalies').disabled=!anomalyEvents.length;showAnomalyList('all');anomalySignature=anomalyFingerprint();render();
 }catch(e){$('anomalyStatus').textContent=e.message;$('anomalySettings').open=true}};
$('downloadAnomalies').onclick=()=>downloadText([['來源','指標','類型','開始','結束','觀測跨度（秒）','極值或結束值','變化量','持續超標','判斷設定'],...anomalyEvents.map(e=>[e.source==='hive'?'內部':'外部',label(e.key),anomalyKind[e.kind],local(new Date(e.start)),local(new Date(e.end)),(e.end-e.start)/1000,e.peak,e.delta??'',e.sustained?'是':'否',JSON.stringify(Object.fromEntries(anomalyIds.map(id=>[id,id==='anomalyShade'?checked(id):value(id)])))])].map(r=>r.map(csvCell).join(',')).join('\n'),'異常標記.csv');
document.addEventListener('change',e=>{if(anomalyNavigating)return;if(e.target.id==='anomalyShade'){if(state.output.length)draw();return}if(anomalyIds.includes(e.target.id)||e.target.matches('#startDate,#endDate,[data-source],#hiveFile,#weatherFile')){invalidateAnomalies();if(state.output.length)draw()}});
const anomalyCreateChart=createChart;createChart=function(canvas,config){if(anomalyActive&&checked('anomalyShade')&&!['co2hour','overlay','difference'].includes(value('chartMode'))){const events=anomalyEvents.filter(e=>['high','low'].includes(e.kind)),shadeShort=value('shadeShort','#e4972a')+'26',shadeLong=value('shadeLong','#be3728')+'38';config.plugins=[...(config.plugins||[]),{id:'anomalyShading',beforeDatasetsDraw(chart){const {ctx,chartArea:a}=chart,x=chart.scales.x;if(!a||!x)return;ctx.save();ctx.beginPath();ctx.rect(a.left,a.top,a.width,a.height);ctx.clip();for(const e of events){const i=chart.data.datasets.findIndex(d=>d.yAxisID===e.key&&Boolean(d.borderDash?.length)===(e.source==='weather'));if(i<0||!chart.isDatasetVisible(i)||e.end<x.min||e.start>x.max)continue;const l=Math.max(a.left,x.getPixelForValue(e.start)),r=Math.min(a.right,x.getPixelForValue(e.end));ctx.fillStyle=e.sustained?shadeLong:shadeShort;ctx.fillRect(l,a.top,Math.max(3,r-l),a.height)}ctx.restore()}}]}return anomalyCreateChart(canvas,config)};
const scanBeforeSignature=$('scanAnomalies').onclick;$('scanAnomalies').onclick=()=>{scanBeforeSignature();anomalySignature=anomalyFingerprint()};
