const state={hive:null,weather:null,charts:[],co2Chart:null,raw:[],weatherEnabled:true,output:[],metrics:{temp:{color:'#e06b3c',title:'溫度 (°C)'},humidity:{color:'#2878b8',title:'相對濕度 (%)'},co2:{color:'#cf493d',title:'CO₂ (ppm)'}}};
const keys=['temp','humidity','co2'],aliases={time:['timestamp','datetime','date time','日期時間','時間','日期','date','time','系統記錄時間'],temp:['temperature','temp','溫度','temperature (°c)','temperature_c','氣溫'],humidity:['humidity','rh','溼度','濕度','humidity (%)','relative humidity'],co2:['co2','carbon dioxide','二氧化碳','co₂','co2(ppm)','co2 ppm']};const $=id=>document.getElementById(id),norm=s=>String(s??'').trim().toLowerCase().replace(/[\s_\-()]/g,''),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),label=k=>({time:'日期／時間 *',temp:'溫度',humidity:'相對濕度',co2:'CO₂'})[k];
function find(h,k){const names=aliases[k]||[];for(const a of names){const exact=h.find(x=>norm(x)===norm(a));if(exact)return exact}return h.find(x=>names.some(a=>norm(x).includes(norm(a))))||''}function decode(b){const c=$('csvEncoding').value,u=new TextDecoder('utf-8').decode(b);return c==='utf-8'?u:c==='big5'?new TextDecoder('big5').decode(b):u.includes('�')?new TextDecoder('big5').decode(b):u}async function read(file){const b=await file.arrayBuffer(),isCsv=/\.csv$/i.test(file.name),wb=isCsv?XLSX.read(decode(b),{type:'string',raw:true}):XLSX.read(b,{type:'array',cellDates:true}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:'',raw:true});if(!rows.length)throw Error(`${file.name} 找不到資料列`);return rows}
function dateFromName(name){const m=name.match(/(20\d{2})[-_](\d{1,2})[-_](\d{1,2})/);return m?new Date(+m[1],+m[2]-1,+m[3]):null}async function load(files,source){try{const batches=await Promise.all([...files].map(async f=>{const rows=await read(f);return rows.map(r=>({...r,__fileDate:dateFromName(f.name)}))}));const rows=batches.flat();state[source]={rows,headers:[...new Set(rows.flatMap(Object.keys).filter(k=>k!=='__fileDate'))],mapping:{},format:'auto'};setup();$(`${source}Status`).textContent=`已載入 ${source==='weather'?`${files.length} 個檔案，`:files[0].name+' · '}${rows.length.toLocaleString()} 筆資料`}catch(e){$(`${source}Status`).textContent=`無法讀取：${e.message}`}}$('hiveFile').onchange=e=>e.target.files.length&&load(e.target.files,'hive');$('weatherFile').onchange=e=>e.target.files.length&&load(e.target.files,'weather');
function setup(){if(!state.hive&&!state.weather)return;$('mappingCard').classList.remove('hidden');$('controlsCard').classList.remove('hidden');let html='';for(const source of ['hive','weather']){const d=state[source];if(!d)continue;html+=`<div class="mapping-group"><h3>${source==='hive'?'蜂箱 SCD30':'外部氣象站（已合併多檔）'}</h3>`;for(const k of ['time','clock',...keys]){if(!(k in d.mapping))d.mapping[k]=k==='clock'?'':find(d.headers,k);html+=`<label>${k==='clock'?'獨立時分秒欄（日期與時間分欄時選擇）':label(k)}<select data-source="${source}" data-key="${k}"><option value="">不使用</option>${d.headers.map(h=>`<option value="${esc(h)}" ${h===d.mapping[k]?'selected':''}>${esc(h)}</option>`).join('')}</select></label>`}html+=`${source==='weather'?`<label class="station-toggle"><input id="weatherEnabled" type="checkbox" ${state.weatherEnabled?'checked':''}> 採用外部氣象站資料</label>`:''}<label>日期格式<select data-format="${source}"><option value="auto" ${d.format==='auto'?'selected':''}>自動辨識</option><option value="ymd" ${d.format==='ymd'?'selected':''}>年／月／日（2026/07/04）</option><option value="dmy" ${d.format==='dmy'?'selected':''}>日／月／年（04/07/2026）</option><option value="mdy" ${d.format==='mdy'?'selected':''}>月／日／年（07/04/2026）</option></select></label></div>`}$('mappingGrid').innerHTML=html;document.querySelectorAll('[data-source]').forEach(e=>e.onchange=()=>{state[e.dataset.source].mapping[e.dataset.key]=e.value;setDates()});document.querySelectorAll('[data-format]').forEach(e=>e.onchange=()=>{state[e.dataset.format].format=e.value;setDates()});if($('weatherEnabled'))$('weatherEnabled').onchange=e=>{state.weatherEnabled=e.target.checked;if(state.output.length)render()};setDates()}
function parse(v,fmt='auto',base=null){
 if(v instanceof Date)return isNaN(v)?null:new Date(+v);
 if(typeof v==='number'&&v>20000&&v<100000){const u=new Date(Math.round((v-25569)*86400000));return new Date(u.getUTCFullYear(),u.getUTCMonth(),u.getUTCDate(),u.getUTCHours(),u.getUTCMinutes(),u.getUTCSeconds())}
 const str=String(v??'').trim();if(!str)return null;
 const clock=str.match(/^(?:(上午|下午|AM|PM)\s*)?(\d{1,2})(?::(\d{1,2}))?(?::(\d{1,2}))?\s*(AM|PM)?$/i);
 if(clock&&base){let h=+clock[2],mi=+(clock[3]||0),se=+(clock[4]||0),ap=clock[1]||clock[5];if(ap)h=h%12+(/下午|PM/i.test(ap)?12:0);if(h>24||mi>59||se>59||(h===24&&(mi||se)))return null;return new Date(base.getFullYear(),base.getMonth(),base.getDate(),h,mi,se)}
 const m=str.match(/^(\d{1,4})[\/年.\-](\d{1,2})[\/月.\-](\d{1,4})日?(.*)$/);if(!m)return null;
 let y,mo,d;if(m[1].length===4||fmt==='ymd'){[y,mo,d]=[+m[1],+m[2],+m[3]]}else if(fmt==='dmy'){[y,mo,d]=[+m[3],+m[2],+m[1]]}else if(fmt==='mdy'){[y,mo,d]=[+m[3],+m[1],+m[2]]}else return null;
 const result=new Date(y,mo-1,d);if(result.getFullYear()!==y||result.getMonth()!==mo-1||result.getDate()!==d)return null;
 const tail=m[4].replace(/^[T\s]+/,'').trim();return tail?parse(tail,fmt,result):result;
}
function rowDate(r,d){
 const base=parse(r[d.mapping.time],d.format,r.__fileDate);if(!base||!d.mapping.clock)return base;
 const c=r[d.mapping.clock];if(c instanceof Date)return new Date(base.getFullYear(),base.getMonth(),base.getDate(),c.getHours(),c.getMinutes(),c.getSeconds());
 if(typeof c==='number'&&c>=0&&c<1){return new Date(base.getFullYear(),base.getMonth(),base.getDate(),0,0,Math.round(c*86400))}
 return parse(c,d.format,base);
}
function datesOf(d){return d?.mapping.time?d.rows.map(r=>rowDate(r,d)).filter(Boolean):[]}
function local(d){const z=n=>String(n).padStart(2,'0');return d.getFullYear()+'-'+z(d.getMonth()+1)+'-'+z(d.getDate())+'T'+z(d.getHours())+':'+z(d.getMinutes())+':'+z(d.getSeconds())}
function setDates(){updatePreview();const hive=datesOf(state.hive).sort((a,b)=>a-b),all=[...hive,...datesOf(state.weather)].sort((a,b)=>a-b),base=hive.length?hive:all;if(!base.length)return;$('startDate').value=local(base[0]);$('endDate').value=local(base.at(-1));$('dataRange').textContent=`SCD30 資料期間：${base[0].toLocaleString('zh-TW')} 至 ${base.at(-1).toLocaleString('zh-TW')}`}
function bucket(t,m){const d=new Date(t);if(m==='raw')return +d;if(m==='5min')d.setMinutes(Math.floor(d.getMinutes()/5)*5,0,0);if(m==='15min')d.setMinutes(Math.floor(d.getMinutes()/15)*15,0,0);if(m==='hour')d.setMinutes(0,0,0);if(m==='day')d.setHours(0,0,0,0);return +d}function keep(k,v){const min=$(`${k}Min`).value,max=$(`${k}Max`).value;return (!min||v>=Number(min))&&(!max||v<=Number(max))}
function calculate(){const start=+new Date($('startDate').value),end=+new Date($('endDate').value),mode=$('aggregation').value,raw=[];for(const source of ['hive','weather']){const d=state[source];if(!d?.mapping.time||(source==='weather'&&!state.weatherEnabled))continue;for(const row of d.rows){const time=rowDate(row,d);if(!time||time<start||time>end)continue;for(const key of keys){const col=d.mapping[key],value=Number(String(row[col]??'').replace(',','.'));if(col&&String(row[col]??'').trim()!==''&&Number.isFinite(value)&&keep(key,value))raw.push({source,key,time:bucket(time,mode),value,original:+time})}}}state.raw=raw;const g=new Map;raw.forEach(x=>{const id=`${x.source}|${x.key}|${x.time}`,v=g.get(id)||{...x,sum:0,n:0};v.sum+=x.value;v.n++;g.set(id,v)});state.output=[...g.values()].map(v=>({...v,value:v.sum/v.n})).sort((a,b)=>a.time-b.time);return raw.length}
function controls(){return keys.map(k=>`<label class="metric"><strong>${label(k)}</strong><input data-metric="${k}" data-prop="color" type="color" value="${state.metrics[k].color}"/><input data-metric="${k}" data-prop="title" type="text" value="${esc(state.metrics[k].title)}"/></label>`).join('')}function timeLabel(t,day){const d=new Date(t),z=n=>String(n).padStart(2,'0');return day?`${z(d.getHours())}:${z(d.getMinutes())}`:`${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())} ${z(d.getHours())}:${z(d.getMinutes())}`}function dataFor(k,source,day=null){return state.output.filter(x=>x.key===k&&x.source===source&&(!day||new Date(x.time).toDateString()===day)).map(x=>({x:timeLabel(x.time,Boolean(day)),y:x.value}))}function xScale(day=false){return{type:'category',ticks:{autoSkip:true,maxTicksLimit:day?12:10},title:{display:true,text:day?'時間':'日期與時間'}}}
function makeSets(k,day=null){return['hive','weather'].filter(s=>dataFor(k,s,day).length).map(s=>({label:s==='hive'?`內部${label(k)}`:`外部${label(k)}（虛線）`,data:dataFor(k,s,day),borderColor:state.metrics[k].color,backgroundColor:'transparent',borderWidth:s==='hive'?2:3,pointRadius:s==='hive'?0:1,borderDash:s==='weather'?[12,7]:[],tension:.12,spanGaps:$('missing').value==='connect',yAxisID:k}))}function opts(scales){return{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom',labels:{boxWidth:48,boxHeight:0}}},scales}}
function draw(){state.charts.forEach(c=>c.destroy());state.charts=[];if(state.co2Chart){state.co2Chart.destroy();state.co2Chart=null}$('co2DailyCard').classList.add('hidden');if($('chartMode').value==='co2hour'){$('charts').innerHTML='';drawCO2Daily();return}const present=keys.filter(k=>state.output.some(x=>x.key===k)),mode=$('chartMode').value;if(mode==='combined'){$('charts').innerHTML='<div class="chart-card"><h3>溫度、相對濕度與 CO₂ 合併圖</h3><canvas id="combined"></canvas></div>';const axes={x:xScale()};present.forEach((k,i)=>axes[k]={position:i?'right':'left',offset:i===2,title:{display:true,text:state.metrics[k].title},grid:{drawOnChartArea:i===0}});state.charts.push(createChart($('combined'),{type:'line',data:{datasets:present.flatMap(k=>makeSets(k))},options:opts(axes)}))}else{let groups=present;if(mode==='daily'){const days=[...new Set(state.output.map(x=>new Date(x.time).toDateString()))];groups=days.flatMap(day=>present.map(k=>`${day}|${k}`))}$('charts').innerHTML=groups.map((x,i)=>{const [day,k]=x.includes('|')?x.split('|'):[null,x];return `<div class="chart-card"><h3>${day?new Date(day).toLocaleDateString('zh-TW')+' · ':''}${esc(state.metrics[k].title)}</h3><canvas id="chart-${i}"></canvas></div>`}).join('');groups.forEach((x,i)=>{const [day,k]=x.includes('|')?x.split('|'):[null,x],sets=makeSets(k,day);state.charts.push(createChart($(`chart-${i}`),{type:'line',data:{datasets:sets},options:opts({x:xScale(Boolean(day)),[k]:{title:{display:true,text:state.metrics[k].title}}})}))})}}
function drawCO2Daily(){const rows=state.raw.filter(x=>x.source==='hive'&&x.key==='co2'),card=$('co2DailyCard');if(!rows.length){card.classList.add('hidden');$('charts').textContent='此期間沒有符合條件的內部 CO₂ 資料。';return}card.classList.remove('hidden');const bins=Array.from({length:24},()=>({sum:0,n:0}));rows.forEach(x=>{const b=bins[new Date(x.original).getHours()];b.sum+=x.value;b.n++});state.hourBins=bins;const active=bins.filter(b=>b.n).length;document.querySelector('#co2DailyCard .chart-note').textContent='使用篩選後原始 CO₂ 逐筆平均，與時間彙整設定無關。涵蓋 '+active+'/24 個小時；共 '+rows.length.toLocaleString()+' 筆。'+(active===1?'僅一個小時有資料：請確認時間預覽及獨立時分秒欄。':'');state.co2Chart=createChart($('co2DailyChart'),{type:'line',data:{labels:bins.map((_,i)=>`${String(i).padStart(2,'0')}:00`),datasets:[{label:'內部 CO₂ 平均',data:bins.map(b=>b.n?b.sum/b.n:null),borderColor:state.metrics.co2.color,backgroundColor:state.metrics.co2.color,borderWidth:2,pointRadius:2,tension:.12,spanGaps:false}]},options:{responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{labels:{boxHeight:0}}},scales:{x:{ticks:{autoSkip:false},title:{display:true,text:'每日時間'}},y:{title:{display:true,text:state.metrics.co2.title}}}}})}
function render(){const n=calculate();if(!n)return alert('請確認日期／時間欄位、日期格式及欲分析的欄位／篩選條件。');$('chartCard').classList.remove('hidden');$('metricControls').innerHTML=controls();document.querySelectorAll('[data-metric]').forEach(e=>e.oninput=x=>{state.metrics[x.target.dataset.metric][x.target.dataset.prop]=x.target.value;draw()});draw();const ts=new Set(state.output.map(x=>x.time));$('qualitySummary').innerHTML=`<div class="quality-item"><strong>${n.toLocaleString()}</strong><span>有效原始數值</span></div><div class="quality-item"><strong>${state.output.length.toLocaleString()}</strong><span>彙整後觀測值</span></div><div class="quality-item"><strong>${ts.size.toLocaleString()}</strong><span>時間點</span></div><div class="quality-item"><strong>${$('aggregation').selectedOptions[0].text}</strong><span>目前彙整尺度</span></div>`}$('renderButton').onclick=render;
document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{const d=datesOf(state.hive).sort((a,b)=>a-b);if(!d.length)return;const end=d.at(-1),n=Number(b.dataset.range);$('endDate').value=local(end);$('startDate').value=local(b.dataset.range==='all'?d[0]:new Date(Math.max(+d[0],+end-n*86400000)))});$('downloadPng').onclick=()=>{const cs=[...document.querySelectorAll('#charts canvas'),...(!$('co2DailyCard').classList.contains('hidden')?[$('co2DailyChart')]:[])].filter(Boolean),o=document.createElement('canvas'),w=Math.max(...cs.map(c=>c.width)),h=cs.reduce((n,c)=>n+c.height,0);o.width=w;o.height=h;const x=o.getContext('2d');x.fillStyle='white';x.fillRect(0,0,w,h);let y=0;cs.forEach(c=>{x.drawImage(c,0,y);y+=c.height});const a=document.createElement('a');a.href=o.toDataURL('image/png');a.download='hive-weather-timeseries.png';a.click()};$('downloadCsv').onclick=()=>{const r=['time,source,metric,value,samples',...state.output.map(x=>`${new Date(x.time).toISOString()},${x.source},${x.key},${x.value},${x.n}`)],a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+r.join('\n')],{type:'text/csv;charset=utf-8'}));a.download='hive-weather-aggregated.csv';a.click()};
function updatePreview(){let el=$('timePreview');if(!el){el=document.createElement('div');el.id='timePreview';$('mappingCard').appendChild(el)}el.innerHTML=['hive','weather'].filter(k=>state[k]).map(k=>{const d=state[k],ds=datesOf(d),bad=d.rows.length-ds.length;return '<p><strong>'+ (k==='hive'?'SCD30':'外站')+' 時間預覽</strong>：'+ds.slice(0,3).map(t=>local(t).replace('T',' ')).join('、')+'；無法解析 '+bad+' 筆。'+(ds.length&&ds.every(t=>t.getHours()===0&&t.getMinutes()===0&&t.getSeconds()===0)?'<br>所有時間都是午夜，請選完整時間欄；若日期與時間分開，請指定「獨立時分秒欄」。':'')+'</p>'}).join('')}

function createChart(canvas,config){if(!canvas.parentElement.classList.contains('canvas-frame')){const frame=document.createElement('div');frame.className='canvas-frame';canvas.parentElement.insertBefore(frame,canvas);frame.appendChild(canvas)}return new Chart(canvas,config)}
