const state={hive:null,weather:null,charts:[],output:[],metrics:{temp:{color:'#e06b3c',title:'溫度 (°C)'},humidity:{color:'#2878b8',title:'相對濕度 (%)'},co2:{color:'#cf493d',title:'CO₂ (ppm)'}}};
const aliases={time:['timestamp','datetime','date time','日期時間','時間','日期','date','time','系統記錄時間'],temp:['temperature','temp','溫度','temperature (°c)','temperature_c','氣溫'],humidity:['humidity','rh','濕度','humidity (%)','relative humidity'],co2:['co2','carbon dioxide','二氧化碳','co₂','co2(ppm)','co2 ppm']};const keys=['temp','humidity','co2'];const $=id=>document.getElementById(id);const norm=s=>String(s??'').trim().toLowerCase().replace(/[\s_\-()]/g,'');const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const label=k=>({time:'日期／時間 *',temp:'溫度',humidity:'相對濕度',co2:'CO₂'})[k];
function find(headers,key){return headers.find(h=>aliases[key].some(a=>norm(h)===norm(a)||norm(h).includes(norm(a))))||''}function decode(buffer){const choice=$('csvEncoding').value,utf=new TextDecoder('utf-8').decode(buffer);if(choice==='utf-8')return utf;if(choice==='big5')return new TextDecoder('big5').decode(buffer);return utf.includes('�')?new TextDecoder('big5').decode(buffer):utf}
async function one(file){const buf=await file.arrayBuffer();let rows;if(/\.csv$/i.test(file.name)){const wb=XLSX.read(decode(buf),{type:'string'});rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:'',raw:false})}else{const wb=XLSX.read(buf,{type:'array',cellDates:true});rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:'',raw:false})}if(!rows.length)throw Error(`${file.name} 找不到資料列`);return rows}
async function load(files,source){try{const rows=(await Promise.all([...files].map(one))).flat();state[source]={rows,headers:[...new Set(rows.flatMap(r=>Object.keys(r)))],mapping:{}};setup();const text=source==='weather'?`${files.length} 個檔案，${rows.length.toLocaleString()} 筆資料`:`${files[0].name} · ${rows.length.toLocaleString()} 筆資料`;$(`${source}Status`).textContent=`已載入 ${text}`}catch(e){$(`${source}Status`).textContent=`無法讀取：${e.message}`}}
$('hiveFile').onchange=e=>e.target.files.length&&load(e.target.files,'hive');$('weatherFile').onchange=e=>e.target.files.length&&load(e.target.files,'weather');
function setup(){if(!state.hive&&!state.weather)return;$('mappingCard').classList.remove('hidden');$('controlsCard').classList.remove('hidden');let html='';for(const source of ['hive','weather']){const d=state[source];if(!d)continue;html+=`<div class="mapping-group"><h3>${source==='hive'?'蜂箱 SCD30':'外部氣象站（已合併多檔）'}</h3>`;for(const key of ['time',...keys]){const guess=find(d.headers,key);d.mapping[key]=d.mapping[key]||guess;html+=`<label>${label(key)}<select data-source="${source}" data-key="${key}"><option value="">不使用</option>${d.headers.map(h=>`<option value="${esc(h)}" ${h===d.mapping[key]?'selected':''}>${esc(h)}</option>`).join('')}</select></label>`}html+='</div>'}$('mappingGrid').innerHTML=html;document.querySelectorAll('[data-source]').forEach(e=>e.onchange=()=>{state[e.dataset.source].mapping[e.dataset.key]=e.value;dates()});dates()}
function date(v){if(v instanceof Date&&!isNaN(v))return v;if(typeof v==='number'&&v>20000&&v<70000)return new Date((v-25569)*86400000);const d=new Date(v);if(!isNaN(d))return d;const m=String(v).match(/(\d{4})\D(\d{1,2})\D(\d{1,2})(?:\D+(\d{1,2}):?(\d{2})?:?(\d{2})?)?/);return m?new Date(+m[1],m[2]-1,+m[3],+(m[4]||0),+(m[5]||0),+(m[6]||0)):null}function sourceDates(d){return d?.mapping.time?d.rows.map(r=>date(r[d.mapping.time])).filter(Boolean):[]}function local(d){const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
function dates(){const all=[...sourceDates(state.hive),...sourceDates(state.weather)].sort((a,b)=>a-b);if(!all.length)return;$('startDate').value=local(all[0]);$('endDate').value=local(all.at(-1));$('dataRange').textContent=`資料期間：${all[0].toLocaleString('zh-TW')} 至 ${all.at(-1).toLocaleString('zh-TW')}`}
function bucket(d,mode){d=new Date(d);if(mode==='raw')return d.getTime();if(mode==='5min')d.setMinutes(Math.floor(d.getMinutes()/5)*5,0,0);if(mode==='15min')d.setMinutes(Math.floor(d.getMinutes()/15)*15,0,0);if(mode==='hour')d.setMinutes(0,0,0);if(mode==='day')d.setHours(0,0,0,0);return d.getTime()}
function calculate(){const start=new Date($('startDate').value).getTime(),end=new Date($('endDate').value).getTime(),mode=$('aggregation').value,raw=[];for(const source of ['hive','weather']){const d=state[source];if(!d?.mapping.time)continue;for(const row of d.rows){const t=date(row[d.mapping.time]);if(!t||t<start||t>end)continue;for(const key of keys){const col=d.mapping[key],value=Number(String(row[col]??'').replace(',','.'));if(col&&Number.isFinite(value))raw.push({source,key,time:bucket(t,mode),value})}}}const groups=new Map;raw.forEach(x=>{const id=`${x.source}|${x.key}|${x.time}`,g=groups.get(id)||{...x,sum:0,n:0};g.sum+=x.value;g.n++;groups.set(id,g)});state.output=[...groups.values()].map(g=>({...g,value:g.sum/g.n}));return raw.length}
function controls(){return keys.map(k=>`<label class="metric"><strong>${label(k)}</strong><input data-metric="${k}" data-prop="color" type="color" value="${state.metrics[k].color}" title="線條顏色"/><input data-metric="${k}" data-prop="title" type="text" value="${esc(state.metrics[k].title)}" title="座標軸標題"/></label>`).join('')}
function render(){const count=calculate();if(!count)return alert('請確認日期／時間欄位，以及溫度、濕度或 CO₂ 欄位。');$('chartCard').classList.remove('hidden');$('metricControls').innerHTML=controls();document.querySelectorAll('[data-metric]').forEach(e=>e.oninput=x=>{state.metrics[x.target.dataset.metric][x.target.dataset.prop]=x.target.value;draw()});draw();quality(count)}
function draw(){state.charts.forEach(c=>c.destroy());state.charts=[];const present=keys.filter(k=>state.output.some(x=>x.key===k));$('charts').innerHTML=present.map(k=>`<div class="chart-card"><h3>${esc(state.metrics[k].title)}</h3><canvas id="chart-${k}"></canvas></div>`).join('');const span=new Date($('endDate').value)-new Date($('startDate').value);for(const key of present){const m=state.metrics[key],sets=['hive','weather'].filter(s=>state.output.some(x=>x.source===s&&x.key===key)).map(source=>({label:source==='hive'?'蜂箱 SCD30':'外部氣象站',data:state.output.filter(x=>x.source===source&&x.key===key).map(x=>({x:x.time,y:x.value})),borderColor:m.color,backgroundColor:m.color,borderWidth:2,pointRadius:span>86400000?0:1.5,borderDash:source==='weather'?[7,4]:[],tension:.12,spanGaps:$('missing').value==='connect'}));state.charts.push(new Chart($(`chart-${key}`),{type:'line',data:{datasets:sets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom'}},scales:{x:{type:'linear',ticks:{callback:v=>new Date(v).toLocaleString('zh-TW',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})},title:{display:true,text:'日期與時間'}},y:{title:{display:true,text:m.title}}}}}))}}
function quality(n){const times=new Set(state.output.map(x=>x.time));$('qualitySummary').innerHTML=`<div class="quality-item"><strong>${n.toLocaleString()}</strong><span>有效原始數值</span></div><div class="quality-item"><strong>${state.output.length.toLocaleString()}</strong><span>彙整後觀測值</span></div><div class="quality-item"><strong>${times.size.toLocaleString()}</strong><span>時間點</span></div><div class="quality-item"><strong>${$('aggregation').selectedOptions[0].text}</strong><span>目前彙整尺度</span></div>`}
document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{const all=[...sourceDates(state.hive),...sourceDates(state.weather)].sort((a,b)=>a-b);if(!all.length)return;const end=all.at(-1),n=Number(b.dataset.range);$('endDate').value=local(end);$('startDate').value=local(b.dataset.range==='all'?all[0]:new Date(Math.max(all[0],new Date(end).setDate(end.getDate()-n))))});$('renderButton').onclick=render;
$('downloadPng').onclick=()=>{const cs=[...document.querySelectorAll('#charts canvas')];if(!cs.length)return;const out=document.createElement('canvas'),w=Math.max(...cs.map(c=>c.width)),h=cs.reduce((n,c)=>n+c.height,0);out.width=w;out.height=h;const ctx=out.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,w,h);let y=0;cs.forEach(c=>{ctx.drawImage(c,0,y);y+=c.height});const a=document.createElement('a');a.href=out.toDataURL('image/png',1);a.download='hive-weather-timeseries.png';a.click()};$('downloadCsv').onclick=()=>{const rows=['time,source,metric,value,samples',...state.output.map(x=>`${new Date(x.time).toISOString()},${x.source},${x.key},${x.value},${x.n}`)];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'}));a.download='hive-weather-aggregated.csv';a.click()};
