/* A short guided route, while preserving the full research controls. */
const guide=document.createElement('nav');guide.className='workflow';guide.setAttribute('aria-label','操作流程');guide.innerHTML='<button type="button" id="goSource"><span>1</span><div>匯入資料<small>Excel／CSV，只需上傳一次</small></div></button><button type="button" id="goPlot"><span>2</span><div>選擇用途<small>製作圖表，或查詢紀錄</small></div></button><button type="button" id="goResult"><span>3</span><div>檢視與下載<small>標示重點，保留分析結果</small></div></button>';sourcePanel.before(guide);
const start=document.createElement('section');start.className='quick-start';start.innerHTML='<div><h3>第一次使用？從這裡開始</h3><p id="readyHint">先匯入蜂箱資料，再選下方用途。外部氣象站資料為選填。</p></div><div class="start-actions"><button id="quickTrend" class="primary">看整段變化</button><button id="quickCycle" class="secondary">看 CO₂ 一天規律</button><button id="quickSearch" class="secondary">找 CO₂ 超標紀錄</button></div><details><summary>這三種操作有什麼不同？</summary><p>整段變化：全期間、每小時平均、三個指標分圖。一天規律：全期間原始 CO₂ 依 00–23 時平均。超標紀錄：查原始 CO₂ 大於 2500 的紀錄，可自行修改門檻。圖表快捷操作會重設日期與數值篩選，但保留外觀及外站開關。</p></details>';tabs.before(start);
const editorPanel=document.querySelector('.chart-editor'),editFold=section('調整圖表外觀與標示（選填）');editorPanel.before(editFold);editFold.appendChild(editorPanel);editFold.classList.add('appearance-fold');
const formatStatus=document.createElement('p');formatStatus.className='quick-note';formatStatus.textContent='先看圖，再展開外觀設定。每張圖下方可指定標示時間點或單張下載。';editFold.before(formatStatus);
// Keep diagnostics available without pushing the next task out of view.
const diagnostics=section('資料品質與計算摘要');$('qualitySummary').before(diagnostics);diagnostics.appendChild($('qualitySummary'));
function ready(){const available=Boolean(state.hive?.rows.length);for(const id of ['quickTrend','quickCycle','quickSearch'])$(id).disabled=!available;$('readyHint').textContent=available?'蜂箱資料已載入。快捷圖表會使用全部日期、清除數值篩選與手動標示，保留外觀設定；也可直接使用下方詳細設定。':'先匯入蜂箱資料，再選下方用途。外部氣象站資料為選填。'}
const beforeEaseSetup=setup;setup=function(){beforeEaseSetup();ready();const preview=$('timePreview');if(preview){let summary=$('sourceTimeHint');if(!summary){summary=document.createElement('p');summary.id='sourceTimeHint';summary.className='quick-note';sourcePanel.after(summary)}summary.textContent=preview.textContent}};
function jump(el){el.scrollIntoView({behavior:'smooth',block:'start'})}
$('goSource').onclick=()=>{sourcePanel.open=true;jump(sourcePanel)};$('goPlot').onclick=()=>jump(tabs);$('goResult').onclick=()=>{const target=queryPage.hidden?$('chartCard'):$('queryResults');if(target.hidden||target.classList.contains('hidden')){jump(queryPage.hidden?$('controlsCard'):queryPage);return}jump(target)};
function quickPlot(mode){if(!state.hive)return;switchPage('plot');resetFilterValues();setDates();$('aggregation').value='hour';$('chartMode').value=mode;$('diurnalStart').value='0';manualLabels.clear();markDirty();render();sourcePanel.open=false;jump($('chartCard'))}
$('quickTrend').onclick=()=>quickPlot('continuous');$('quickCycle').onclick=()=>quickPlot('co2hour');$('quickSearch').onclick=()=>{switchPage('query');$('clearQuery').click();$('queryPreset').click();sourcePanel.open=false;$('runQuery').click();jump(queryPage)};
const oldMarkDirty=markDirty;markDirty=function(){oldMarkDirty();$('renderButton').textContent='套用並更新圖表'};
const beforeEaseRender=render;render=function(){beforeEaseRender();if(!state.dirty)$('renderButton').textContent='更新圖表'};$('renderButton').onclick=render;
$('renderButton').textContent='製作圖表';document.querySelector('footer').textContent='蜂箱環境資料分析台 v10 · 資料僅在瀏覽器處理 · 請以台灣時區使用';ready();
