const plotQueryButton=document.createElement('button');plotQueryButton.className='primary';plotQueryButton.textContent='將查詢結果繪成圖表';plotQueryButton.id='plotQueryResults';document.querySelector('.query-results-heading').appendChild(plotQueryButton);
const showPageBeforePlotAction=showQueryPage;showQueryPage=function(){showPageBeforePlotAction();plotQueryButton.disabled=!queryRows.length};
const subsetBanner=document.createElement('div');subsetBanner.className='explanation';subsetBanner.hidden=true;subsetBanner.innerHTML='<p id="subsetDescription"></p><button id="clearQuerySubset" class="secondary">恢復完整資料繪圖</button>';$('controlsCard').prepend(subsetBanner);
function clearQuerySubset(){state.querySubset=null;subsetBanner.hidden=true;markDirty()}
$('clearQuerySubset').onclick=()=>{clearQuerySubset();render()};
plotQueryButton.onclick=()=>{if(!queryRows.length)return;const subset={hive:new Set(),weather:new Set()};let lo=Infinity,hi=-Infinity;for(const r of queryRows){subset[r.source].add(r.originalRow);lo=Math.min(lo,r.time);hi=Math.max(hi,r.time)}state.querySubset=subset;resetFilterValues();$('startDate').value=local(new Date(lo));$('endDate').value=local(new Date(hi));$('chartMode').value='continuous';$('aggregation').value='hour';$('missing').value='gap';$('xTickInterval').value='auto';state.weatherEnabled=subset.weather.size>0;if($('weatherEnabled'))$('weatherEnabled').checked=state.weatherEnabled;manualLabels.clear();$('subsetDescription').textContent='目前只繪製查詢命中的 '+queryRows.length.toLocaleString()+' 筆紀錄：'+querySummary+' 圖表預設為這些紀錄的每小時平均，可自行調整；未選日期不納入計算。';subsetBanner.hidden=false;switchPage('plot');markDirty();render();$('chartCard').scrollIntoView({behavior:'smooth',block:'start'})};
document.addEventListener('change',e=>{if(e.target.matches('[data-source],[data-format],#hiveFile,#weatherFile'))clearQuerySubset()});
const runPanel=document.createElement('details');runPanel.className='editor-section';runPanel.innerHTML='<summary>CO₂ 超標時段統計</summary><p class="help-text">先查詢 CO₂「大於」或「大於等於」門檻。此統計使用相同日期與來源的完整紀錄辨識恢復正常、缺值與資料中斷，不只看命中的點。</p><label>允許相鄰紀錄的最大間隔（秒）<input id="eventGap" type="number" min="1" max="86400" value="90"></label><p class="help-text">內部約每 30 秒一筆，可用 90 秒；外站每小時一筆，可改為 5400 秒。超過此間隔即另起一段。「觀測跨度」只計最後與第一筆超標紀錄的時間差；單點為 0，不代表實際超標只持續 0 秒，也不推估缺測期間。</p><button id="calculateEvents" class="secondary">統計超標時段</button><button id="downloadEvents" class="secondary" disabled>下載時段 CSV</button><p id="eventStatus" role="status"></p><div class="query-table-wrap"><table><thead><tr><th>來源</th><th>起始</th><th>最後超標紀錄</th><th>觀測跨度（秒）</th><th>峰值（ppm）</th><th>筆數</th><th>結束判定</th></tr></thead><tbody id="eventRows"></tbody></table></div>';$('queryResults').appendChild(runPanel);
let currentEvents=[];
function clearEvents(){currentEvents=[];$('eventRows').replaceChildren();$('eventStatus').textContent='';$('downloadEvents').disabled=true}
const previousInvalidate=invalidateQuery;invalidateQuery=function(message){previousInvalidate(message);clearEvents()};
$('eventGap').oninput=clearEvents;
$('calculateEvents').onclick=()=>{clearEvents();try{if(!completedQuery||completedQuery.metric!=='co2'||!['gt','gte'].includes(completedQuery.op))throw Error('請先完成 CO₂ 大於或大於等於門檻的查詢。');const seconds=Number($('eventGap').value);if(!Number.isInteger(seconds)||seconds<1||seconds>86400)throw Error('最大間隔請輸入 1 至 86400 秒的整數。');currentEvents=exceedanceRuns(queryScope,Number(completedQuery.min),completedQuery.op==='gte',seconds*1000);$('eventRows').innerHTML=currentEvents.slice(0,200).map(r=>'<tr>'+[r.source==='hive'?'蜂箱內部':'外部氣象站',local(new Date(r.start)),local(new Date(r.end)),r.spanSeconds,r.peak,r.n,r.endReason].map(x=>'<td>'+esc(String(x))+'</td>').join('')+'</tr>').join('');$('eventStatus').textContent='共 '+currentEvents.length+' 段，觀測跨度合計 '+currentEvents.reduce((sum,r)=>sum+r.spanSeconds,0)+' 秒（非估計實際超標總時長）。表格最多顯示前 200 段，下載包含全部。';$('downloadEvents').disabled=!currentEvents.length}catch(e){$('eventStatus').textContent=e.message}};
$('downloadEvents').onclick=()=>{if(!currentEvents.length)return;downloadText([['來源','起始時間','最後超標時間','觀測跨度（秒）','峰值（ppm）','筆數','結束判定','門檻','允許間隔（秒）'],...currentEvents.map(r=>[r.source==='hive'?'蜂箱內部':'外部氣象站',local(new Date(r.start)),local(new Date(r.end)),r.spanSeconds,r.peak,r.n,r.endReason,completedQuery.min,$('eventGap').value])].map(row=>row.map(csvCell).join(',')).join('\n'),'CO₂超標時段.csv')};
// Re-running a query with unchanged controls must also invalidate the event table.
const runBeforeEvents=$('runQuery').onclick;$('runQuery').onclick=async()=>{clearEvents();await runBeforeEvents()};
document.querySelector('footer').textContent='蜂箱環境資料分析台 v11 · 資料僅在瀏覽器處理 · 請以台灣時區使用';
