const sourcePanel=section('資料來源：上傳檔案與確認欄位',true);sourcePanel.id='sourcePanel';const uploads=document.querySelector('.upload-grid');uploads.before(sourcePanel);sourcePanel.appendChild(uploads);sourcePanel.appendChild(document.querySelector('.encoding').closest('.editor-section'));
const mappingFold=section('資料欄位與時間檢查（自動配對）');$('mappingCard').before(mappingFold);mappingFold.appendChild($('mappingCard'));sourcePanel.appendChild(mappingFold);
const tabs=document.createElement('div');tabs.className='page-tabs';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','工作分頁');tabs.innerHTML='<button id="plotTab" role="tab" aria-selected="true" aria-controls="plotPage">製作圖表</button><button id="queryTab" role="tab" aria-selected="false" aria-controls="queryPage" tabindex="-1">查詢資料</button>';sourcePanel.after(tabs);
const plotPage=document.createElement('section');plotPage.id='plotPage';plotPage.setAttribute('role','tabpanel');plotPage.setAttribute('aria-labelledby','plotTab');tabs.after(plotPage);plotPage.append($('controlsCard'),$('chartCard'));
const emptyPlot=document.createElement('p');emptyPlot.id='emptyPlot';emptyPlot.className='explanation';emptyPlot.textContent='先在上方「資料來源」匯入檔案，再選日期與圖表。';plotPage.prepend(emptyPlot);
const advanced=section('進階分析（選填）');$('controlsCard').appendChild(advanced);const filterFold=document.querySelector('.filter-panel').parentElement;advanced.appendChild(filterFold);advanced.appendChild(document.querySelector('.callout'));advanced.appendChild($('missing').closest('.editor-section'));
const queryPage=document.createElement('section');queryPage.id='queryPage';queryPage.className='card';queryPage.hidden=true;queryPage.setAttribute('role','tabpanel');queryPage.setAttribute('aria-labelledby','queryTab');queryPage.innerHTML=`<h2>查詢原始資料</h2><p class="query-help">選日期、設條件、查看結果。不受圖表篩選、平均或外站顯示開關影響；每列保留同一筆紀錄的溫度、濕度與 CO₂。</p>
<div class="query-fields"><label>查哪一份資料<select id="querySource"><option value="hive">蜂箱內部</option><option value="weather">外部氣象站</option><option value="both">內部與外部</option></select></label><label>查哪幾天<select id="queryDateMode"><option value="all">全部日期</option><option value="days">指定一天／多天</option><option value="range">連續日期區間</option></select></label></div>
<div id="queryDays" hidden><div class="query-date-add"><label>選擇日期<input id="queryDay" type="date"></label><button id="addQueryDay" class="secondary" type="button">加入日期</button></div><div id="queryDayChips" class="query-chips"></div></div>
<div id="queryRange" class="query-fields" hidden><label>開始日期<input id="queryStart" type="date"></label><label>結束日期（含當日）<input id="queryEnd" type="date"></label></div>
<div class="query-fields"><label>查詢指標<select id="queryMetric"><option value="co2">CO₂（ppm）</option><option value="temp">溫度（°C）</option><option value="humidity">相對濕度（%）</option></select></label><label>符合條件<select id="queryOp"><option value="none">不限數值</option><option value="gt">大於 ＞</option><option value="gte">大於等於 ≥</option><option value="lt">小於 ＜</option><option value="lte">小於等於 ≤</option><option value="range">介於（含上下限）</option></select></label><label id="queryMinLabel" hidden>數值／下限<input id="queryMin" type="number" step="any" placeholder="例如 2500"></label><label id="queryMaxLabel" hidden>上限<input id="queryMax" type="number" step="any"></label></div>
<div class="query-actions"><button id="runQuery" class="primary">開始查詢</button><button id="queryPreset" class="secondary">內部 CO₂ ＞ 2500</button><button id="clearQuery" class="secondary">清除查詢條件</button></div><p id="queryStatus" role="status" aria-live="polite">尚未查詢。請先匯入資料。</p>
<section id="queryResults" hidden><div class="query-results-heading"><strong id="queryCount"></strong><label>排序<select id="querySort"><option value="time">時間由早到晚</option><option value="latest">時間由晚到早</option><option value="co2">CO₂ 由高到低</option></select></label><button id="exportQuery" class="secondary">下載全部查詢結果 CSV</button></div><p id="queryApplied" class="query-help"></p><div class="query-table-wrap" tabindex="0" role="region" aria-label="查詢結果表格"><table><thead><tr><th>時間（台灣本地時間）</th><th>資料來源</th><th>溫度（°C）</th><th>相對濕度（%）</th><th>CO₂（ppm）</th></tr></thead><tbody id="queryRows"></tbody></table></div><div class="query-pagination"><button id="queryPrevious" class="secondary">上一頁</button><span id="queryPageLabel"></span><button id="queryNext" class="secondary">下一頁</button></div></section>`;plotPage.after(queryPage);
let queryDays=new Set(),queryRows=[],queryPageIndex=0,queryRevision=0,querySummary='',queryScope=[],completedQuery=null;const queryPageSize=100;
function switchPage(name){const query=name==='query';plotPage.hidden=query;queryPage.hidden=!query;for(const id of ['plot','query']){const active=id===name;$(id+'Tab').setAttribute('aria-selected',String(active));$(id+'Tab').tabIndex=active?0:-1}if(!query)[...state.charts,...(state.co2Chart?[state.co2Chart]:[])].forEach(c=>c.resize())}
$('plotTab').onclick=()=>switchPage('plot');$('queryTab').onclick=()=>switchPage('query');tabs.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const name=e.key==='Home'?'plot':e.key==='End'?'query':$('plotTab').getAttribute('aria-selected')==='true'?'query':'plot';switchPage(name);$(name+'Tab').focus()}};
tabs.addEventListener('click',()=>{if(state.hive||state.weather)sourcePanel.open=false});
function queryControls(){const mode=$('queryDateMode').value,op=$('queryOp').value;$('queryDays').hidden=mode!=='days';$('queryRange').hidden=mode!=='range';$('queryMinLabel').hidden=op==='none';$('queryMaxLabel').hidden=op!=='range'}
function invalidateQuery(message='查詢條件已變更，請按「開始查詢」。'){queryRevision++;queryScope=[];completedQuery=null;queryRows=[];$('queryResults').hidden=true;$('queryStatus').textContent=message;$('runQuery').disabled=false;queryControls()}
function drawDayChips(){$('queryDayChips').replaceChildren();[...queryDays].sort().forEach(day=>{const button=document.createElement('button');button.className='secondary';button.textContent=day+' ×';button.setAttribute('aria-label','移除 '+day);button.onclick=()=>{queryDays.delete(day);drawDayChips();invalidateQuery()};$('queryDayChips').appendChild(button)})}
$('addQueryDay').onclick=()=>{const day=$('queryDay').value;if(!day){$('queryStatus').textContent='請先選擇日期。';return}queryDays.add(day);drawDayChips();invalidateQuery()};
for(const id of ['querySource','queryDateMode','queryMetric','queryOp','queryMin','queryMax','queryStart','queryEnd'])$(id).oninput=()=>invalidateQuery();
function currentQuery(){return {source:$('querySource').value,dateMode:$('queryDateMode').value,days:[...queryDays],start:$('queryStart').value,end:$('queryEnd').value,metric:$('queryMetric').value,op:$('queryOp').value,min:$('queryMin').value,max:$('queryMax').value}}
function sortQuery(){const mode=$('querySort').value;queryRows.sort((a,b)=>mode==='co2'?(b.co2??-Infinity)-(a.co2??-Infinity)||a.time-b.time:mode==='latest'?b.time-a.time:a.time-b.time);queryPageIndex=0;showQueryPage()}
function showQueryPage(){const n=queryRows.length,pages=Math.max(1,Math.ceil(n/queryPageSize));queryPageIndex=Math.min(queryPageIndex,pages-1);$('queryRows').innerHTML=queryRows.slice(queryPageIndex*queryPageSize,(queryPageIndex+1)*queryPageSize).map(r=>'<tr><td>'+esc(local(new Date(r.time)).replace('T',' '))+'</td><td>'+(r.source==='hive'?'蜂箱內部':'外部氣象站')+'</td>'+['temp','humidity','co2'].map(k=>'<td>'+(r[k]===null?'—':r[k])+'</td>').join('')+'</tr>').join('');$('queryCount').textContent='符合條件 '+n.toLocaleString()+' 筆';$('queryPageLabel').textContent=n?'第 '+(queryPageIndex+1)+'／'+pages+' 頁 · 每頁最多 100 筆':'沒有符合條件的資料';$('queryPrevious').disabled=queryPageIndex===0;$('queryNext').disabled=queryPageIndex>=pages-1;$('exportQuery').disabled=!n;$('queryApplied').textContent=querySummary}
$('querySort').onchange=sortQuery;$('queryPrevious').onclick=()=>{queryPageIndex--;showQueryPage()};$('queryNext').onclick=()=>{queryPageIndex++;showQueryPage()};
$('runQuery').onclick=async()=>{
 const q=currentQuery(),revision=++queryRevision;queryRows=[];queryScope=[];completedQuery=null;$('queryResults').hidden=true;try{validateQuery(q);const sources=(q.source==='both'?['hive','weather']:[q.source]).filter(s=>state[s]);if(!sources.length)throw Error('請先上傳要查詢的資料。');if(sources.some(s=>!state[s].mapping.time))throw Error('請先在資料欄位中選擇日期時間欄。');if(q.op!=='none'&&!sources.some(s=>state[s].mapping[q.metric]))throw Error('所選資料沒有此指標欄位，請確認欄位配對。');$('runQuery').disabled=true;$('queryStatus').textContent='正在查詢原始資料…';await new Promise(r=>setTimeout(r,0));let invalid=0,total=0,missing=0;const found=[];
 for(const source of sources){const d=state[source];for(let i=0;i<d.rows.length;i++){if(i%10000===0){await new Promise(r=>setTimeout(r,0));if(revision!==queryRevision)return}total++;const raw=d.rows[i],date=rowDate(raw,d);if(!date){invalid++;continue}const row={originalRow:raw,source,time:+date,day:local(date).slice(0,10)};for(const k of keys)row[k]=queryNumber(raw[d.mapping[k]]);if(q.op!=='none'&&row[q.metric]===null)missing++;if(matchesQuery(row,{...q,op:'none'}))queryScope.push(row);if(matchesQuery(row,q))found.push(row)}}
 if(revision!==queryRevision)return;queryRows=found;completedQuery={...q};const dates=q.dateMode==='all'?'全部日期':q.dateMode==='days'?q.days.sort().join('、'):q.start+' 至 '+q.end;querySummary=dates+'；'+(q.op==='none'?'不限數值':label(q.metric)+' '+filterOperators[q.op]+' '+q.min+(q.op==='range'?' ～ '+q.max:''))+'；原始紀錄，未平均。';$('queryStatus').textContent='查詢完成：檢查 '+total.toLocaleString()+' 筆；無效時間 '+invalid+' 筆'+(q.op==='none'?'':'；查詢指標缺值／非數值 '+missing+' 筆')+'。缺值顯示 —，不當作 0。';$('queryResults').hidden=false;sortQuery();
 }catch(e){if(revision===queryRevision)$('queryStatus').textContent=e.message}finally{if(revision===queryRevision)$('runQuery').disabled=false}
};
$('clearQuery').onclick=()=>{$('querySource').value='hive';$('queryDateMode').value='all';$('queryMetric').value='co2';$('queryOp').value='none';$('queryMin').value='';$('queryMax').value='';queryDays.clear();drawDayChips();invalidateQuery('已清除查詢條件。')};
$('queryPreset').onclick=()=>{$('querySource').value='hive';$('queryMetric').value='co2';$('queryOp').value='gt';$('queryMin').value='2500';invalidateQuery('已設定內部 CO₂ ＞ 2500；日期條件保留，請按「開始查詢」。')};
$('exportQuery').onclick=()=>{if(!queryRows.length)return;downloadText([['時間','資料來源','溫度（°C）','相對濕度（%）','CO₂（ppm）'],...queryRows.map(r=>[local(new Date(r.time)),r.source==='hive'?'蜂箱內部':'外部氣象站',r.temp,r.humidity,r.co2])].map(r=>r.map(csvCell).join(',')).join('\n'),'原始資料查詢結果.csv')};
const setupBeforeQuery=setup;setup=function(){setupBeforeQuery();$('emptyPlot').hidden=true;invalidateQuery('資料已更新，請設定條件後查詢。');const d=state.hive||state.weather,dates=datesOf(d);if(dates.length){let lo=Infinity,hi=-Infinity;dates.forEach(d=>{lo=Math.min(lo,+d);hi=Math.max(hi,+d)});$('queryDay').value=local(new Date(lo)).slice(0,10);$('queryStart').value=$('queryDay').value;$('queryEnd').value=local(new Date(hi)).slice(0,10)}};
document.addEventListener('change',event=>{if(event.target.matches('[data-source],[data-format],#hiveFile,#weatherFile'))invalidateQuery('資料或欄位已變更，請重新查詢。')});
const setupWithQuery=setup;setup=function(){setupWithQuery();sourcePanel.querySelector('summary').textContent='資料來源 · '+['hive','weather'].filter(s=>state[s]).map(s=>(s==='hive'?'內部 ':'外部 ')+state[s].rows.length.toLocaleString()+' 筆').join('／')+'（點此更換或檢查）'};
document.querySelector('.hero h2').textContent='看趨勢，或找出你要的紀錄。';document.querySelector('.hero p:not(.eyebrow)').textContent='匯入一次資料，切換「製作圖表」或「查詢資料」。';document.querySelector('.hero-note').hidden=true;document.querySelector('footer').textContent='蜂箱環境資料分析台 v9 · 資料僅在瀏覽器處理 · 請以台灣時區使用';
