// Rainfall amounts are summed, never averaged; missing/trace readings are not zero.
function rainfallNumber(raw){const s=String(raw??'').trim();if(!s)return null;const n=Number(s);return Number.isFinite(n)&&n>=0?n:null}
function aggregateRainfall(rows,mode){const seen=new Map(),groups=new Map(),stats={missing:0,duplicates:0,conflicts:0};for(const r of rows){if(seen.has(r.time)){stats.duplicates++;if(seen.get(r.time)!==r.value){stats.conflicts++;seen.set(r.time,null)}}else seen.set(r.time,r.value)}for(const [time,v]of seen){if(v===null){stats.missing++;continue}const t=bucket(new Date(time),mode),g=groups.get(t)||{time:t,value:0,n:0};g.value+=v;g.n++;groups.set(t,g)}return {rows:[...groups.values()].sort((a,b)=>a.time-b.time),stats}}
const rainOption=document.createElement('option');rainOption.value='rainfall';rainOption.textContent='降水量與環境數據比較';$('chartMode').appendChild(rainOption);
const rainControls=document.createElement('div');rainControls.className='tick-settings';rainControls.hidden=true;rainControls.innerHTML='<label>降水量要對比哪個指標？<select id="rainCompareMetric"><option value="co2">CO₂</option><option value="temp">溫度</option><option value="humidity">相對濕度</option></select></label><label>對比資料來源<select id="rainCompareSource"><option value="hive">蜂箱內部</option><option value="weather">外部氣象站</option><option value="both">內部與外部</option></select></label><label>降水量顏色<input id="rainColor" type="color" value="#7556a3"></label><p class="help-text">降水量使用右軸（mm）；環境指標使用左軸。降水量按觀測時間加總，其他指標維持平均。小於一小時的尺度自動改為每小時；缺值與微量降水代碼不當作 0。日加總依觀測時間分日，不等同氣象站官方日雨量。</p><p id="rainStatus" role="status"></p>';$('modeExplanation').after(rainControls);
settingIds.push('rainCompareMetric','rainCompareSource','rainColor');
modeDescriptions.rainfall='以外部氣象站降水量，對照蜂箱或氣象站的溫度、濕度、CO₂。使用兩個不同單位的縱軸。';
const explainBeforeRain=explain;explain=function(){explainBeforeRain();rainControls.hidden=value('chartMode')!=='rainfall'};
const modeBeforeRain=effectiveMode;effectiveMode=function(){return value('chartMode')==='rainfall'&&['raw','5min','15min'].includes(value('aggregation'))?'hour':modeBeforeRain()};
const setupBeforeRain=setup;setup=function(){setupBeforeRain();const d=state.weather;if(!d)return;if(!Object.hasOwn(d.mapping,'rain'))d.mapping.rain=d.headers.find(h=>/降水量|降雨量|雨量|precp|precipitation/i.test(h))||'';const card=document.querySelector('[data-source="weather"]').closest('.mapping-group'),field=document.createElement('label');field.textContent='降水量（mm）';const select=document.createElement('select');select.dataset.source='weather';select.dataset.key='rain';for(const h of ['',...d.headers]){const op=document.createElement('option');op.value=h;op.textContent=h||'不使用';op.selected=h===d.mapping.rain;select.appendChild(op)}select.onchange=()=>{d.mapping.rain=select.value;markDirty()};field.appendChild(select);card.querySelector('.mapping-value-fields').appendChild(field)};
for(const id of ['rainCompareMetric','rainCompareSource','rainColor'])$(id).onchange=()=>{markDirty();if(state.hive||state.weather)render()};
const drawBeforeRain=draw;draw=function(){if(value('chartMode')!=='rainfall'){drawBeforeRain();return}state.charts.forEach(c=>c.destroy());state.charts=[];if(state.co2Chart){state.co2Chart.destroy();state.co2Chart=null}$('co2DailyCard').classList.add('hidden');$('charts').replaceChildren();state.rainOutput=[];$('rainStatus').textContent='';const d=state.weather;if(!d?.mapping.rain||!state.weatherEnabled){$('charts').textContent='請匯入外部氣象站資料、指定降水量欄位，並開啟外站顯示。';return}const start=+new Date(value('startDate')),end=+new Date(value('endDate')),records=[];for(const row of d.rows){if(state.querySubset&&!state.querySubset.weather?.has(row))continue;const date=rowDate(row,d);if(date&&+date>=start&&+date<=end)records.push({time:+date,value:rainfallNumber(row[d.mapping.rain])})}const result=aggregateRainfall(records,effectiveMode());state.rainOutput=result.rows;const k=value('rainCompareMetric'),source=value('rainCompareSource'),sets=makeSets(k).filter(s=>source==='both'||(source==='weather')===Boolean(s.borderDash?.length));if(!sets.length||!result.rows.length){$('charts').textContent='所選期間沒有可比較的降水量或指定指標。若目前限定查詢結果，請先恢復完整資料繪圖。';return}const step=effectiveMode()==='day'?86400000:3600000,points=[];result.rows.forEach((r,i)=>{if(i&&r.time-result.rows[i-1].time>step*1.5)points.push({x:result.rows[i-1].time+step,y:null});points.push({x:r.time,y:r.value})});const rainSet={label:'外部降水量（mm）',customName:true,metricKey:'rain',yAxisID:'rain',data:points,borderColor:value('rainColor'),backgroundColor:value('rainColor'),borderDash:[4,4],spanGaps:false};insertChart('rain-chart','降水量與'+label(k)+'比較',[...sets,rainSet],{x:xScale(),[k]:{position:'left',title:{display:true,text:state.metrics[k].title}},rain:{position:'right',beginAtZero:true,title:{display:true,text:'降水量 (mm)'},grid:{drawOnChartArea:false}}});$('rainStatus').textContent='降水量有效時段 '+result.rows.length+'；缺值／微量／衝突時刻 '+result.stats.missing+'；重複紀錄 '+result.stats.duplicates+'（衝突 '+result.stats.conflicts+'）。逐日數值為已取得觀測值加總，缺測時可能不完整。'};
const csvBeforeRain=currentCsv;currentCsv=function(){if(value('chartMode')!=='rainfall')return csvBeforeRain();const k=value('rainCompareMetric'),source=value('rainCompareSource');return [['時間','資料來源','指標','數值','統計方式','樣本數'],...state.output.filter(r=>r.key===k&&(source==='both'||r.source===source)).map(r=>[local(new Date(r.time)),r.source==='hive'?'蜂箱內部':'外部氣象站',label(k),r.value,'平均',r.n]),...(state.rainOutput||[]).map(r=>[local(new Date(r.time)),'外部氣象站','降水量（mm）',r.value,'加總',r.n])].map(r=>r.map(csvCell).join(',')).join('\n')};
