// Rainfall amounts are summed, never averaged; missing/trace readings are not zero.
function rainfallNumber(raw){const s=String(raw??'').trim();if(!s)return null;const n=Number(s);return Number.isFinite(n)&&n>=0?n:null}
function aggregateRainfall(rows,mode){const seen=new Map(),groups=new Map(),stats={missing:0,duplicates:0,conflicts:0};for(const r of rows){if(seen.has(r.time)){stats.duplicates++;if(seen.get(r.time)!==r.value){stats.conflicts++;seen.set(r.time,null)}}else seen.set(r.time,r.value)}for(const [time,v]of seen){if(v===null){stats.missing++;continue}const t=bucket(new Date(time),mode),g=groups.get(t)||{time:t,value:0,n:0};g.value+=v;g.n++;groups.set(t,g)}return {rows:[...groups.values()].sort((a,b)=>a.time-b.time),stats}}
const rainOption=document.createElement('option');rainOption.value='rainfall';rainOption.textContent='降水量與環境數據比較';$('chartMode').appendChild(rainOption);
const rainControls=document.createElement('div');rainControls.className='rain-comparison';rainControls.hidden=true;
rainControls.innerHTML='<fieldset><legend>同時比較的資料（可複選）</legend><div class="rain-series-grid">'+['hive','weather'].map(source=>'<div class="rain-source"><strong>'+(source==='hive'?'蜂箱內部':'外部氣象站')+'</strong>'+keys.map(k=>'<label class="check-tile"><input type="checkbox" id="rain-'+source+'-'+k+'" '+(k==='humidity'?'checked':'')+'><span>'+label(k)+'</span></label>').join('')+'</div>').join('')+'</div></fieldset><details class="rain-method"><summary>降水量計算方式</summary><p>降水量按觀測時間加總，其他指標取平均。最小尺度為每小時；缺值與微量代碼不視為 0。日加總依觀測時間分日，不等同官方日雨量；缺測時可能不完整。數值篩選只套用環境指標，不篩除降水量。</p></details><p id="rainStatus" role="status"></p>';
$('modeExplanation').after(rainControls);
const rainStyle=document.createElement('div');rainStyle.className='metric-controls rain-style';rainStyle.innerHTML='<label class="metric"><strong>外部降水量</strong><input id="rainColor" type="color" value="#7556a3" aria-label="降水量線條顏色"><input id="rainAxisTitle" type="text" value="降水量 (mm)" aria-label="降水量座標軸標題"></label>';$('metricControls').after(rainStyle);
const palette=document.createElement('div');palette.className='series-palette';$('metricControls').before(palette);palette.append($('metricControls'),rainStyle);
const rainSelectionIds=['hive','weather'].flatMap(source=>keys.map(k=>'rain-'+source+'-'+k));
settingIds.push(...rainSelectionIds,'rainColor','rainAxisTitle');
function selectedRainSeries(){return ['hive','weather'].flatMap(source=>keys.filter(k=>checked('rain-'+source+'-'+k)).map(k=>({source,key:k})))}
modeDescriptions.rainfall='勾選比較資料；降水量使用獨立座標軸。';
const explainBeforeRain=explain;explain=function(){explainBeforeRain();rainControls.hidden=value('chartMode')!=='rainfall'};
const modeBeforeRain=effectiveMode;effectiveMode=function(){return value('chartMode')==='rainfall'&&['raw','5min','15min'].includes(value('aggregation'))?'hour':modeBeforeRain()};
const setupBeforeRain=setup;setup=function(){setupBeforeRain();const d=state.weather;if(!d)return;if(!Object.hasOwn(d.mapping,'rain'))d.mapping.rain=d.headers.find(h=>/降水量|降雨量|雨量|precp|precipitation/i.test(h))||'';const card=document.querySelector('[data-source="weather"]').closest('.mapping-group'),field=document.createElement('label');field.textContent='降水量（mm）';const select=document.createElement('select');select.dataset.source='weather';select.dataset.key='rain';for(const h of ['',...d.headers]){const op=document.createElement('option');op.value=h;op.textContent=h||'不使用';op.selected=h===d.mapping.rain;select.appendChild(op)}select.onchange=()=>{d.mapping.rain=select.value;markDirty()};field.appendChild(select);card.querySelector('.mapping-value-fields').appendChild(field)};
for(const id of [...rainSelectionIds,'rainColor','rainAxisTitle'])$(id).onchange=()=>{markDirty();if(state.hive||state.weather)render()};
const resetBeforeRain=applyDefaultFormat;applyDefaultFormat=function(){resetBeforeRain();$('rainColor').value='#7556a3';$('rainAxisTitle').value='降水量 (mm)'};
const drawBeforeRain=draw;draw=function(){if(value('chartMode')!=='rainfall'){drawBeforeRain();return}state.charts.forEach(c=>c.destroy());state.charts=[];if(state.co2Chart){state.co2Chart.destroy();state.co2Chart=null}$('co2DailyCard').classList.add('hidden');$('charts').replaceChildren();state.rainOutput=[];$('rainStatus').textContent='';const d=state.weather;if(!d?.mapping.rain||!state.weatherEnabled){$('charts').textContent='請匯入外部氣象站資料、指定降水量欄位，並開啟外站顯示。';return}const start=+new Date(value('startDate')),end=+new Date(value('endDate')),records=[];for(const row of d.rows){if(state.querySubset&&!state.querySubset.weather?.has(row))continue;const date=rowDate(row,d);if(date&&+date>=start&&+date<=end)records.push({time:+date,value:rainfallNumber(row[d.mapping.rain])})}const result=aggregateRainfall(records,effectiveMode());state.rainOutput=result.rows;const selection=selectedRainSeries(),sets=[],missing=[];if(!selection.length){$('charts').textContent='請至少勾選一項比較資料。';return}for(const {source,key:k}of selection){const matches=makeSets(k).filter(s=>(source==='weather')===Boolean(s.borderDash?.length)&&s.data.some(p=>p.y!==null&&Number.isFinite(p.y)));if(matches.length)sets.push(...matches);else missing.push((source==='hive'?'內部':'外部')+label(k))}if(!sets.length||!result.rows.length){$('charts').textContent='所選期間沒有可比較的降水量或指定指標。若目前限定查詢結果，請先恢復完整資料繪圖。';return}const step=effectiveMode()==='day'?86400000:3600000,points=[];result.rows.forEach((r,i)=>{if(i&&r.time-result.rows[i-1].time>step*1.5)points.push({x:result.rows[i-1].time+step,y:null});points.push({x:r.time,y:r.value})});const rainSet={label:'外部降水量（mm）',customName:true,metricKey:'rain',yAxisID:'rain',data:points,borderColor:value('rainColor'),backgroundColor:value('rainColor'),borderDash:[4,4],spanGaps:false};const metrics=keys.filter(k=>sets.some(s=>s.yAxisID===k)),axes={x:xScale()};metrics.forEach((k,i)=>axes[k]={position:i%2?'right':'left',title:{display:true,text:state.metrics[k].title},grid:{drawOnChartArea:i===0}});axes.rain={position:'right',beginAtZero:true,title:{display:true,text:value('rainAxisTitle')},grid:{drawOnChartArea:false}};insertChart('rain-chart','降水量與'+metrics.map(label).join('、')+'比較',[...sets,rainSet],axes);$('rainStatus').textContent=(missing.length?'無可用資料：'+missing.join('、')+'。 ':'')+'降水量有效時段 '+result.rows.length+'；缺值／微量／衝突時刻 '+result.stats.missing+'；重複紀錄 '+result.stats.duplicates+'（衝突 '+result.stats.conflicts+'）。'};
const csvBeforeRain=currentCsv;currentCsv=function(){if(value('chartMode')!=='rainfall')return csvBeforeRain();const selection=selectedRainSeries();return [['時間','資料來源','指標','數值','統計方式','樣本數'],...state.output.filter(r=>selection.some(s=>r.key===s.key&&r.source===s.source)).map(r=>[local(new Date(r.time)),r.source==='hive'?'蜂箱內部':'外部氣象站',label(r.key),r.value,'平均',r.n]),...(state.rainOutput||[]).map(r=>[local(new Date(r.time)),'外部氣象站','降水量（mm）',r.value,'加總',r.n])].map(r=>r.map(csvCell).join(',')).join('\n')};
